import {StyleSheet} from 'react-native';
import {
  Colors,
  Sizes,
  Height,
  parseSizeHeight,
  parseSizeWidth,
  parseSize,
  FontStyles,
} from '~theme';

export default styles = StyleSheet.create({
  stylesContainer: {
    gap: parseSizeWidth(-4),
    alignItems: 'center',
    justifyContent: 'center',
  },
  btnHeader: {
    borderRadius: 6,
    backgroundColor: Colors.neutrals_100,
    borderWidth: 1,
    borderColor: Colors.neutrals_300,
    alignItems: 'center',
    justifyContent: 'center',
    width: parseSize(31),
    height: parseSize(31),
  },
  boxBtnHeader: {
    gap: parseSize(10),
    flexDirection: 'row',
  },
  headerText: {
    fontSize: Sizes.text_subtitle1,
    fontWeight: '500',
    color: Colors.brand_01,
    fontFamily: FontStyles.InterRegular,
  },
  calendarTheme: {
    calendarBackground: Colors.neutrals_100,
    textSectionTitleColor: Colors.semantics_Black,
    monthTextColor: '#198B4D',
    textMonthFontWeight: '500',
    textDayHeaderFontWeight: '500',
    textDayFontSize: Sizes.text_subtitle1,
    textMonthFontSize: Sizes.text_subtitle1,
    textDayHeaderFontSize: Sizes.text_tagline1,
  },
  wrapDate: {
    borderRadius: 6,
    backgroundColor: Colors.neutrals_100,
    borderWidth: 1,
    borderColor: Colors.neutrals_200,
    alignItems: 'center',
    justifyContent: 'center',
    width: parseSize(31),
    height: parseSize(31),
  },
  textDate: {
    fontSize: Sizes.text_subtitle1,
    fontWeight: '500',
    textAlign: 'center',
    color: Colors.neutrals_700,
    fontFamily: FontStyles.InterRegular,
  },
  rangeDate: {
    backgroundColor: Colors.semantics_Green_03,
    borderWidth: 0,
    borderRadius: 0,
    width: '150%',
    zIndex: -1,
  },
  selectedDate: {
    backgroundColor: Colors.semantics_Green_03,
    borderColor: Colors.semantics_Green_02,
  },
  disabledText: {
    color: Colors.neutrals_300,
  },
  disabledDate: {
    backgroundColor: Colors.neutrals_50,
  },
  itemInputDate: {
    flex: 0.5,
  },
  contentInputDate: {
    fontFamily: FontStyles.InterRegular,
    fontSize: Sizes.text_subtitle1,
    fontWeight: '500',
    color: Colors.semantics_Black,
  },
  titleInputDate: {
    fontFamily: FontStyles.InterRegular,
    fontSize: Sizes.text_tagline1,
    fontWeight: '500',
    color: Colors.neutrals_500,
  },
  lineGrey: {
    width: parseSizeWidth(90),
    height: parseSizeHeight(5),
    borderRadius: 100,
    backgroundColor: Colors.neutrals_300,
    marginBottom: Sizes.spacing_4_Height,
  },
  line: {
    borderRightWidth: 1,
    borderColor: Colors.neutrals_700,
    height: '70%',
    alignSelf: 'center',
  },
  inputDate: {
    borderRadius: parseSize(16),
    backgroundColor: Colors.neutrals_100,
    borderWidth: 1,
    borderColor: Colors.neutrals_300,
    marginBottom: parseSizeHeight(10),
    flexDirection: 'row',
    gap: parseSizeWidth(14),
    paddingHorizontal: parseSizeWidth(7),
    paddingVertical: parseSizeHeight(5),
    width: parseSizeWidth(342),
  },
  calendar: {
    backgroundColor: Colors.neutrals_100,
    height: parseSize(384),
  },
  boxCalendar: {
    paddingHorizontal: parseSizeWidth(10),
    paddingVertical: parseSizeHeight(10),
    borderRadius: parseSize(16),
    backgroundColor: Colors.neutrals_100,
    borderWidth: 1,
    borderColor: Colors.neutrals_300,
    height: parseSizeHeight(465),
    width: parseSizeWidth(342),
  },
  button: {
    flexDirection: 'row',
    gap: parseSizeWidth(15),
    alignSelf: 'flex-end',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: Colors.background,
    paddingHorizontal: Sizes.paddingWidth,
    paddingVertical: Sizes.paddingHeight,
    alignItems: 'center',
    borderTopLeftRadius: parseSize(24),
    borderTopRightRadius: parseSize(24),
    position: 'relative',
  },
  modalContainer: {
    backgroundColor: Colors.backgroundShowPopup,
    margin: 0,
    height: Height,
  },
  container: {
    justifyContent: 'flex-end',
    margin: 0,
    height: Height,
  },
});
