import { StyleSheet } from 'react-native';
import {
  Sizes,
  Colors,
  FontStyles,
  parseSizeHeight,
  parseSizeWidth,
} from '~theme';

export default styles = StyleSheet.create({
  linearGradient: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  scanCircle: {
    position: 'absolute',
    width: 100,
    height: 100,
    borderWidth: 1,
    zIndex: 2,
    borderRadius: 70,
    borderColor: Colors.neutrals_300,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.neutrals_100,
    transform: [{ rotate: '-45deg' }],
  },

  intoLeft: {
    transform: [{ rotate: '-45deg' }],
    justifyContent: 'center',
    alignItems: 'center',
    gap: parseSizeHeight(20),
    flex: 1,
    right: parseSizeWidth(-10),
    top: parseSizeWidth(-10),
  },
  intoRight: {
    transform: [{ rotate: '-45deg' }],
    justifyContent: 'center',
    alignItems: 'center',
    gap: parseSizeHeight(20),
    flex: 1,
    right: parseSizeWidth(10),
    top: parseSizeWidth(10),
  },
  intoBottom: {
    transform: [{ rotate: '-45deg' }],
    justifyContent: 'center',
    alignItems: 'center',
    gap: parseSizeHeight(20),
    flex: 1,
    paddingBottom: parseSizeHeight(20),
  },
  intoTop: {
    transform: [{ rotate: '-45deg' }],
    justifyContent: 'center',
    alignItems: 'center',
    gap: parseSizeHeight(20),
    flex: 1,
    paddingTop: parseSizeHeight(20),
  },
  txtMenuClick: {
    width: parseSizeWidth(90),
    fontSize: Sizes.text_subtitle2,
    fontWeight: '600',
    textAlign: 'center',
    fontFamily: FontStyles.InterSemiBold,
    color: Colors.neutrals_50,
  },
  txtMenu: {
    width: parseSizeWidth(90),
    fontSize: Sizes.text_subtitle2,
    fontWeight: '600',
    textAlign: 'center',
    color: Colors.brand_01,
    fontFamily: FontStyles.InterSemiBold,
  },
  itemBottom: {
    flex: 0.5,
    borderWidth: 0.5,
    overflow: 'hidden',
    borderColor: Colors.neutrals_300,
    borderBottomRightRadius: parseSizeWidth(172),
    justifyContent: 'center',
  },
  itemLeft: {
    flex: 0.5,
    borderWidth: 0.5,
    overflow: 'hidden',
    borderColor: Colors.neutrals_300,
    borderBottomLeftRadius: parseSizeWidth(172),
    justifyContent: 'center',
  },
  itemRight: {
    flex: 0.5,
    borderWidth: 0.5,
    overflow: 'hidden',
    borderColor: Colors.neutrals_300,
    borderTopRightRadius: parseSizeWidth(172),
    justifyContent: 'center',
  },
  itemTop: {
    flex: 0.5,
    borderWidth: 0.5,
    overflow: 'hidden',
    borderColor: Colors.neutrals_300,
    borderTopLeftRadius: parseSizeWidth(172),
    justifyContent: 'center',
  },
  itemTop_Bottom: {
    flexDirection: 'row',
    flex: 0.5,
  },
  menu: {
    width: parseSizeWidth(344),
    height: parseSizeWidth(344),
    borderRadius: parseSizeWidth(172),
    backgroundColor: Colors.neutrals_100,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    transform: [{ rotate: '45deg' }],
  },
  body: {
    width: '100%',
    height: '100%',
    backgroundColor: Colors.backgroundShowPopup,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    zIndex: 1,
  },
});
