import {StyleSheet} from 'react-native';
import {
  Colors,
  Sizes,
  parseSizeHeight,
  parseSizeWidth,
  FontStyles,
  Width,
} from '~theme';

export default styles = StyleSheet.create({
  container: {
    margin: 0,
    flex: 1,
  },
  header: {
    height: Sizes.spacing_9_Height,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: Sizes.spacing_4_Width,
  },
  boddy: {
    flex: 1,
    paddingHorizontal: Sizes.paddingWidth,
    paddingVertical: Sizes.paddingHeight,
    alignItems: 'center',
    gap: Sizes.paddingHeight,
  },
  bottom: {
    height: parseSizeHeight(104),
    width: Width,
    backgroundColor: Colors.neutrals_100,
    shadowColor: 'rgba(66, 71, 76, 0.32)',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowRadius: 8,
    shadowOpacity: 0.25,
    elevation: 5,
    borderTopLeftRadius: Sizes.spacing_5_Width,
    borderTopRightRadius: Sizes.spacing_5_Width,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'flex-end',
  },

  txtMenu: {
    width: parseSizeWidth(70),
    fontSize: Sizes.text_tagline1,
    fontWeight: '600',
    textAlign: 'center',
    color: Colors.brand_01,
    fontFamily: FontStyles.InterSemiBold,
  },
  itemBottom: {
    flex: 0.5,
    borderWidth: 0.5,
    overflow: 'hidden',
    borderColor: Colors.neutrals_300,
    borderBottomRightRadius: 172,
    justifyContent: 'center',
  },
  itemLeft: {
    flex: 0.5,
    borderWidth: 0.5,
    overflow: 'hidden',
    borderColor: Colors.neutrals_300,
    borderBottomLeftRadius: 172,
    justifyContent: 'center',
  },
  itemRight: {
    flex: 0.5,
    borderWidth: 0.5,
    overflow: 'hidden',
    borderColor: Colors.neutrals_300,
    borderTopRightRadius: 172,
    justifyContent: 'center',
  },
  itemTop: {
    flex: 0.5,
    borderWidth: 0.5,
    overflow: 'hidden',
    borderColor: Colors.neutrals_300,
    borderTopLeftRadius: 172,
    justifyContent: 'center',
  },
  itemTop_Bottom: {
    flexDirection: 'row',
    flex: 0.5,
  },
  menu: {
    width: 278,
    height: 278,
    borderRadius: 172,
    backgroundColor: Colors.neutrals_100,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    transform: [{rotate: '45deg'}],
  },
  intoItem: {
    transform: [{rotate: '-45deg'}],
    justifyContent: 'center',
    alignItems: 'center',
    gap: parseSizeHeight(15),
    flex: 1,
  },
  intoBottom: {
    paddingBottom: parseSizeHeight(15),
  },
  intoTop: {
    paddingTop: parseSizeHeight(15),
  },
  intoLeft: {
    paddingLeft: parseSizeWidth(15),
  },
  intoRight: {
    paddingRight: parseSizeWidth(15),
  },
  scanCircle: {
    position: 'absolute',
    width: 80,
    height: 80,
    borderWidth: 1,
    zIndex: 2,
    borderRadius: 70,
    borderColor: Colors.neutrals_300,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.neutrals_100,
    transform: [{rotate: '-45deg'}],
  },
  choseFuntion: {
    paddingHorizontal: Sizes.paddingWidth,
    width: Width,
  },
  wrapFavFuntion: {
    gap: Sizes.spacing_4_Height,
    marginBottom: Sizes.paddingHeight,
  },
  wrapFuntion: {
    marginBottom: parseSizeHeight(2),
    gap: Sizes.spacing_4_Height,
  },
  txtTitle: {
    fontFamily: FontStyles.InterRegular,
    fontSize: Sizes.text_subtitle1,
    fontWeight: '500',

    textAlign: 'left',
    color: Colors.semantics_Black,
  },
  boxFuntion: {
    borderRadius: 16,
    borderStyle: 'solid',
    borderWidth: 1,
    borderColor: Colors.neutrals_300,
    paddingHorizontal: Sizes.spacing_3_Width,
    paddingVertical: parseSizeHeight(10),
    gap: Sizes.spacing_3_Height,
  },
  itemFuntion: {
    backgroundColor: Colors.neutrals_100,
    borderStyle: 'solid',
    borderBottomWidth: 1,
    borderColor: Colors.neutrals_300,
    paddingHorizontal: parseSizeWidth(10),
    paddingTop: parseSizeHeight(10),
    paddingBottom: parseSizeHeight(15),
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: parseSizeWidth(21),
    alignItems: 'center',
  },
  itemLastFuntion: {
    borderBottomWidth: 0,
  },
  txtContent: {
    fontFamily: FontStyles.InterRegular,
    fontSize: Sizes.text_subtitle1,
    fontWeight: '500',

    textAlign: 'left',
    color: Colors.neutrals_700,
    flex: 1,
  },
  input: {
    height: parseSizeHeight(48),
    borderRadius: 100,
    backgroundColor: Colors.neutrals_100,
    borderStyle: 'solid',
    borderWidth: 1,
    borderColor: Colors.neutrals_300,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    paddingHorizontal: parseSizeWidth(25),
    gap: Sizes.spacing_5_Width,
  },
  textInput: {
    flex: 1,
    height: parseSizeHeight(48),
    fontFamily: FontStyles.InterRegular,
    fontSize: Sizes.textDefault,
    fontWeight: '500',

    textAlign: 'left',
    color: Colors.neutrals_700,
  },
});
