import {StyleSheet} from 'react-native';
import {
  Colors,
  Sizes,
  FontStyles,
  Width,
  Height,
  parseSize,
  parseSizeHeight,
  parseSizeWidth,
} from '~theme';

export default styles = StyleSheet.create({
  svgBottomBackground: {
    position: 'absolute',
    bottom: parseSizeHeight(-50),
    left: parseSizeWidth(-30),
    width: parseSizeWidth(167),
    height: parseSizeHeight(167),
    borderRadius: parseSize(100),
  },
  svgTopBackground: {
    position: 'absolute',
    top: parseSizeHeight(-30),
    right: parseSizeWidth(-30),
    width: parseSizeWidth(145),
    height: parseSizeHeight(145),
  },
  dotLight: {
    width: parseSizeWidth(48),
    height: parseSizeHeight(6),
    borderRadius: parseSize(100),
    backgroundColor: Colors.brand_01,
  },
  dotsContainer: {
    paddingTop: Sizes.spacing_5_Height,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'flex-start',
    gap: 10,
  },
  dot: {
    width: 6,
    height: 6,
    backgroundColor: '#DDDDE3',
    borderRadius: 5,
  },
  imageSales: {
    width: Width * 0.87,
    height: Height * 0.18,
  },
  Notifi: {
    alignSelf: 'center',
    justifyContent: 'center',
  },
  sales: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: Sizes.spacing_5_Height,
  },
  txtButtonPressed: {
    color: Colors.brand_01,
  },
  buttonPressed: {
    borderRadius: parseSize(16),
    borderWidth: 2,
    borderColor: Colors.brand_01,
    shadowColor: 'rgba(0, 0, 0, 0.2)',
    shadowOffset: {width: 1, height: 2},
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 5,
  },
  txtButton: {
    fontFamily: FontStyles.InterRegular,
    fontSize: Sizes.text_subtitle2,
    fontWeight: '500',
    color: '#7E808A',
    textAlign: 'center',
  },
  button: {
    width: parseSizeWidth(97),
    height: parseSizeHeight(96),
    borderRadius: parseSize(16),
    backgroundColor: '#F9F9FB',
    borderWidth: 1,
    borderColor: 'rgba(221, 221, 227, 1.0)',
    alignItems: 'center',
    paddingHorizontal: parseSizeWidth(6),
    paddingVertical: parseSizeHeight(13),
    justifyContent: 'space-between',
  },
  txtResult: {
    fontFamily: FontStyles.InterRegular,
    fontSize: Sizes.text_h4,
    fontWeight: '600',
    color: '#F9F9FB',
  },
  txtTitle: {
    fontFamily: FontStyles.InterRegular,
    fontSize: Sizes.text_subtitle1,
    fontWeight: '500',

    color: '#F9F9FB',
  },
  wrapTotalOrder: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    zIndex: 1,
  },
  txtResulOrderOfDay: {
    fontFamily: FontStyles.InterRegular,
    fontSize: Sizes.text_h3,
    fontWeight: '600',
    color: '#F9F9FB',
    zIndex: 1,
  },
  txtOrderOfDay: {
    fontFamily: FontStyles.InterRegular,
    fontSize: Sizes.text_h6,
    fontWeight: '500',
    color: '#F9F9FB',
    zIndex: 1,
    width: parseSizeWidth(177),
  },
  wrapOrderOfDay: {
    zIndex: 1,
  },
  quantityOrder: {
    borderRadius: parseSize(24),
    paddingHorizontal: Sizes.spacing_6_Width,
    paddingTop: Sizes.spacing_6_Height,
    paddingBottom: parseSizeHeight(6),
    gap: parseSizeHeight(16),
    justifyContent: 'center',
    position: 'relative',
    overflow: 'hidden',
    width: parseSizeWidth(146.1),
    height: parseSizeHeight(134.2),
  },
  buttonRight: {
    justifyContent: 'space-between',
    marginVertical: 3,
  },
  groupButtonUnder: {
    flexDirection: 'row',
    // gap: parseSizeHeight(24),
    marginTop: parseSizeHeight(24),
    justifyContent: 'space-between',
  },
  InforOrder: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: 'red',
    width: parseSizeWidth(220),
    height: parseSizeHeight(216),
  },
  leftSite: {
    alignItems: 'flex-start',
  },
  rightSite: {
    flexDirection: 'column',
    gap: parseSizeHeight(24),
  },
  wrapTotalOrderOfDay: {
    width: parseSizeWidth(220),
    height: parseSizeHeight(216),
    // gap: parseSizeHeight(10),
    paddingHorizontal: Sizes.paddingWidth,
    paddingVertical: Sizes.paddingHeight,
    borderRadius: parseSizeWidth(24),
    overflow: 'scroll',
    justifyContent: 'space-between',
  },
  wrapGroupContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  body: {
    flex: 1,
  },
  content: {
    flex: 1,
    paddingHorizontal: Sizes.paddingWidth,
  },
  container: {
    flex: 1,
    backgroundColor: Colors.background,
    paddingHorizontal: 0,
    margin: 0,
  },
});
